### PR TITLE
Make splitAndTrim parse more inteligently...

### PR DESCRIPTION
**Pull request by alexandernst**
... by making it understand that a space after a range token ('>', '<', '=') can be threated like a typo instead of like an error. Example '<= '.

Also, remove all whitespaces instead of just leading/ending spaces, as there might be spaces between a range token and a version number. Example: '>= 2.5.2'

### CODE REVIEW

**Comment by alexandernst** [comment]
This is a fix for https://github.com/blang/semver/issues/25

**Comment by blang** [comment]
Looks good so far, would you please add corresponding tests

**Comment by alexandernst** [comment]
Yes, give me an hour :)

**Comment by blang** [comment]
No hurry, BTW could that be implemented more easily changing
https://github.com/bitnami/semver/blob/1bd75d4ebca54fb6425a171b5d54d99a7a9d26e0/range.go#L212
```
func splitComparatorVersion(s string) (string, string, error)
```

When i have time, i will have a better look at the code, but `splitComparatorVersion` looks like the better place for adding your implementation

**Comment by alexandernst** [comment]
The problem is that `splitAndTrim` would pass wrong data to the codeflow and by the time `splitComparatorVersion` get's access to the different chunks, there would already be a problem.

Moreover, it actually makes sense this code to be inside `splitAndTrimp`, as lexicographically speaking that code is the code path that should deal with whitespaces, trimming, splitting and so on.

`splitComparatorVersion` should do, as the name of the function says, just split the operator from the version.

**Comment by alexandernst** [comment]
Oh, didn't see your edit until I published my comment.

**Comment by alexandernst** [comment]
Ok, tests are ddone (that took less than I expected!)

**Comment by alexandernst** [comment]
@cbandy As @blang said, it would make more sense first to fix how the entire splitting logic works, so I'd  rather avoid big code changes in this function. But I like the idea!

**Comment by blang** [comment]
Looks good so far, thanks for adding the tests. I will have a closer look in the next days

**Comment by alexandernst** [comment]
Thank you @blang , please ping me if there is anything else I can do to get this merged.

**Pull request merged**
