### PR TITLE
Fix Ci, add go 1.11 to travis and fix linter issues

### PR DESCRIPTION
**Pull request by hanzei**

### CODE REVIEW

**Comment by hanzei** [comment]
@blang ping. If you want, I can try help you merging some of the PRs.

**Comment by hanzei** [comment]
@blang This should be ready to merge.

**Comment by hanzei** [comment]
@blang ping

**Comment by matfax** [comment]
@blang Any feedback on this?
459dade seems to be necessary to fix the build config.

**Comment by blang** [comment]
Thanks for the patience. LGTM

**Pull request merged**
